spring:
  application:
    name: res-demo
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create